name: development-build
on:
  push:
    branches:
      - development
jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm i -g @angular/cli typescript
      - run: npm i
      - run: cd client && npm i
