name: build-and-deploy
on:
  push:
    branches:
      - 'development'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Build both projects
        run: |
          npm i -g @angular/cli typescript && npm i
          cd client && npm i && cd ..
          zip -r application.zip ./ -x *.DS_Store .git/\* node_modules/\* client/node_modules/\*

      - name: Cache zipped application
        uses: actions/cache@v2
        with:
          path: application.zip
          key: cached-zipper-application

      - name: Check result
        run: |
          echo "Check result"
          ls -al

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Get cached zipped application
        uses: actions/cache@v2
        with:
          path: application.zip
          key: cached-zipper-application

      - name: Check result
        run: |
          echo "Check result"
          ls -al

      - name: Deploy to AWS EC2
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: 'application.zip'
          REMOTE_HOST: 'ec2-18-195-52-54.eu-central-1.compute.amazonaws.com'
          REMOTE_USER: 'ec2-user'
          TARGET: '~/'
